### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by jnunez101** [TapWithUs/tap-python-sdk#1]
Is there a plan for adding the ability use this sdk on Linux?

**Comment by ilouzl** [comment]
It's in our backlog - even though I can't commit to a specific date at this point. We'll be happy to receive contributions from developers for this task.

**Comment by raucha** [comment]
Hello @ilouzl .

Thank you for great product.
I love this device. So cool. 

I developed linux support (not parfect for now but work).
Would  you review it?

P.S. Is this contribute satisfy developer contest's application requirements? ...No?
https://www.tapwithus.com/developer-contest-rules/

**Comment by ilouzl** [comment]
Thanks @raucha.
I'll review your PR.
Follow the "How to Enter" guidelines [here](https://www.tapwithus.com/developer-contest-rules/) to check your eligibility.

**Comment by meisam** [comment]
I am also working on linux support. I wasn't aware @raucha's work but it look's there is a lot of overlap

**Comment by meisam** [comment]
Here is my PR: #3

**Comment by ilouzl** [comment]
Resolved with #3
