### ISSUE TITLE
AttributeError: 'TapLinuxSDK' object has no attribute 'set_haptic_command'

### ISSUE THREAD

**Issue by Cobertos** [TapWithUs/tap-python-sdk#11]
Was following the documentation and it looks like this isn't supported on Linux? Would be nice if that module implemented that function.

EDIT: Actually, it only looks like it's in the documentation, and not implemented in any of the platform-specific modules?

**Comment by ilouzl** [comment]
You are absolutely right.
It's a total mishap of ours...
The command is actually ```send_vibration_sequence```. 
Docs are fixed at [0.4.0](https://github.com/TapWithUs/tap-python-sdk/commit/23ef6d5d67e33fbb2170bb0ed0d665e82a9f1ecf)
