### ISSUE TITLE
Linux support of Tap

### ISSUE THREAD

**Issue by wxjames** [TapWithUs/tap-python-sdk#13]
Recently I came across some problems using the python SDK on a Linux system. The Tap is already connected with the Bluetooth. However, when I run "example_linux.py" provided in python SDK, the following error will occur: "bleak.exc.BleakError: Device with address DA:83:20:92:44:42 was not found".

Then I changed the bleak version from 0.11.0 to 0.6.4. Another error would occur: "bleak.exc.BleakError: org.bluez.Error.Failed: Software caused connection abort". Has anyone encountered the same problem and has any suggestions to solve this problem?

**Comment by omair-khalid** [comment]
Have you tried turning off the Developer's mode? I experience problems with my connection when developer mode is on. 

I do need to use the raw data in Developer's mode but unfortunately, I can't get it in Linux because of this problems. Would be great if it could be fixed.

**Comment by ilouzl** [comment]
Linux is supported since #1  thanks to @meisam
