### ISSUE TITLE
Not able to use Raw Input Mode on Windows

### ISSUE THREAD

**Issue by richparks92** [TapWithUs/tap-python-sdk#6]
I'm unable to see any input data coming in when using Raw Sensor mode, on Windows 10 with Python 3.7.9. I'm able to use the "controller" mode, and log taps to the console as they come in. However, when in raw mode, there doesn't seem to be any feedback. I've confirmed:

- Tap device is paired and connected to my laptop
- Developer mode is [ON]
- Input mode is set to "raw"

Is there something I'm missing or doing wrong?

Here is my code:
```
from tapsdk import TapSDK, TapInputMode
from tapsdk.models import AirGestures

tap_instance = []
tap_identifiers = []


def on_connect(identifier, name, fw):
    print(identifier + " Tap: " + str(name), " FW Version: ", fw)
    if identifier not in tap_identifiers:
        tap_identifiers.append(identifier)
    print("Connected taps:")
    for identifier in tap_identifiers:
        print(identifier)


def on_disconnect(identifier):
    print("Tap has disconnected")
    if identifier in tap_identifiers:
        tap_identifiers.remove(identifier)
    for identifier in tap_identifiers:
        print(identifier)

def on_raw_sensor_data(identifier, raw_sensor_data):
    print(raw_sensor_data)
    print("sensed")
    # if raw_sensor_data.GetPoint(1).z > 2000 and raw_sensor_data.GetPoint(2).z > 2000 and raw_sensor_data.GetPoint(3).z > 2000 and raw_sensor_data.GetPoint(4).z > 2000:
    #     tap_instance.set_input_mode(TapInputMode("controller"), identifier)


def main():
    global tap_instance
    tap_instance = TapSDK()
    tap_instance.run()
    
    tap_instance.register_connection_events(on_connect)
    tap_instance.register_disconnection_events(on_disconnect)
    tap_instance.register_raw_data_events(on_raw_sensor_data)
    tap_instance.set_input_mode(TapInputMode("raw",[2,1,4]))    

    while True:
        pass


if __name__ == "__main__":
    main()
```

Here are the logs:
> [2020-09-15 05:58:35] TAPLib info # TAP Manager Started. @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPManager.cs:Start(99)
> [2020-09-15 05:58:36] TAPLib info # Device Watcher Starting @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPManager.cs:RestartDeviceWatcher(199)
> input mode: Raw sensors Mode
> [2020-09-15 05:58:36] TAPLib info # Device Watcher added proc. @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPManager.cs:dw_added(338)
> [2020-09-15 05:58:36] TAPLib info # Found Connected Device Tap_D078210 @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPManager.cs:dw_added(354)
> [2020-09-15 05:58:36] TAPLib info # Tap_D078210 Is a new device. Checking if it's a TAP @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPManager.cs:dw_added(357)
> [2020-09-15 05:58:36] TAPLib info # Device Watcher Enumeration Completed. @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPManager.cs:dw_enum_completed(153)
> [2020-09-15 05:58:43] TAPLib info # Found Characteristic c3ff0002-1d8b-40fd-a56f-c7bd5d0f3370 for Service TAP @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(523)
> [2020-09-15 05:58:43] TAPLib info # Found Characteristic c3ff0003-1d8b-40fd-a56f-c7bd5d0f3370 for Service TAP @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(523)
> [2020-09-15 05:58:43] TAPLib info # Found Characteristic TAP DATA for Service TAP @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(523)
> [2020-09-15 05:58:43] TAPLib info # Found Characteristic MOUSE DATA for Service TAP @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(523)
> [2020-09-15 05:58:43] TAPLib info # Found Characteristic AIR GESTURES DATA for Service TAP @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(523)
> [2020-09-15 05:58:43] TAPLib info # Found Characteristic c3ff0007-1d8b-40fd-a56f-c7bd5d0f3370 for Service TAP @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(523)
> [2020-09-15 05:58:43] TAPLib info # Found Characteristic c3ff0008-1d8b-40fd-a56f-c7bd5d0f3370 for Service TAP @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(523)
> [2020-09-15 05:58:43] TAPLib info # Found Characteristic TAP UI COMMANDS for Service TAP @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(523)
> [2020-09-15 05:58:44] TAPLib info # Found Characteristic c3ff000b-1d8b-40fd-a56f-c7bd5d0f3370 for Service TAP @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(523)
> [2020-09-15 05:58:44] TAPLib info # Found Characteristic NUS_RX for Service NUS @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(550)
> [2020-09-15 05:58:44] TAPLib info # Found Characteristic NUS_TX for Service NUS @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(550)
> [2020-09-15 05:58:44] TAPLib info # Found Characteristic 00002a29-0000-1000-8000-00805f9b34fb for Service DEVICE INFORMATION @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(569)
> [2020-09-15 05:58:44] TAPLib info # Found Characteristic 00002a25-0000-1000-8000-00805f9b34fb for Service DEVICE INFORMATION @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(569)
> [2020-09-15 05:58:44] TAPLib info # Found Characteristic 00002a27-0000-1000-8000-00805f9b34fb for Service DEVICE INFORMATION @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(569)
> [2020-09-15 05:58:44] TAPLib info # Found Characteristic FW VERSION for Service DEVICE INFORMATION @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(569)
> [2020-09-15 05:58:44] TAPLib info # Found Characteristic 00002a28-0000-1000-8000-00805f9b34fb for Service DEVICE INFORMATION @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(569)
> [2020-09-15 05:58:44] TAPLib info # Found Characteristic 00002a50-0000-1000-8000-00805f9b34fb for Service DEVICE INFORMATION @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPDevice.cs:GetTAPPropertiesAsync(569)
> [2020-09-15 05:58:44] TAPLib info # Found a connected TAP: Tap_D078210 (BluetoothLE#BluetoothLE74:df:bf:8d:f5:7a-f4:60:a0:a7:80:cb). Making it ready... @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPManager.cs:dw_added(365)
> [2020-09-15 05:58:44] TAPLib info # TAP is Ready:Tap_D078210 (BluetoothLE#BluetoothLE74:df:bf:8d:f5:7a-f4:60:a0:a7:80:cb) @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPManager.cs:OnTapReady(238)
> BluetoothLE#BluetoothLE74:df:bf:8d:f5:7a-f4:60:a0:a7:80:cb Tap: Tap_D078210  FW Version:  20600
> Connected taps:
> BluetoothLE#BluetoothLE74:df:bf:8d:f5:7a-f4:60:a0:a7:80:cb
> [2020-09-15 06:01:36] TAPLib info # TAP disconnected: Tap_D078210 (BluetoothLE#BluetoothLE74:df:bf:8d:f5:7a-f4:60:a0:a7:80:cb) @ C:\Users\Tapper\Documents\GitHub\tap-standalonewin-sdk\TAPWinSDK\TAPManager.cs:dw_removed(171)

**Comment by odedtap** [comment]
Hi,

When your code starts running, this line only runs once and might not be registered by Tap before the connection is established:
tap_instance.set_input_mode(TapInputMode("raw",[2,1,4]))
Adding a few seconds delay with time.sleep(time_sec) before this line verifies it's a timing issue.

It's probably better to add that line to an event-based function, such as 'on_connect', which you're already using:

```
def on_connect(identifier, name, fw):
    print(identifier + " Tap: " + str(name), " FW Version: ", fw)
    if identifier not in tap_identifiers:
        tap_identifiers.append(identifier)
    print("Connected taps:")
    for identifier in tap_identifiers:
        print(identifier)
    tap_instance.set_input_mode(TapInputMode("raw", [2, 1, 4]))
```

This way the mode will be set when the connection is already established.
Let us know if this solves the issue.

**Comment by richparks92** [comment]
@odedtap made changes based on your suggestion and that looks like it did the trick! Thank you.
